version: "3.8"

services:
  db:
    image: postgres:15
    container_name: poc_export_db
    restart: always
    environment:
      POSTGRES_DB: poc_db
      POSTGRES_USER: poc_user
      POSTGRES_PASSWORD: poc_pass
    ports:
      - "5432:5432"
    volumes:
      - ../db-data:/var/lib/postgresql/data

  middleware:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: middleware_export_app
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: db # muy importante: apunta al servicio 'db', no a localhost
      DB_PORT: 5432
      DB_USER: poc_user
      DB_PASSWORD: poc_pass
      DB_NAME: poc_db
    ports:
      - "3001:3001"
    depends_on:
      - db
